export const ADD_COLLECTION = 'ADD_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
